// Code generated by qtc from "index.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line templates/index.qtpl:1
package templates

//line templates/index.qtpl:1
import "github.com/catatsuy/private-isu/webapp/golang/types"

//line templates/index.qtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line templates/index.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line templates/index.qtpl:3
func StreamContentPage(qw422016 *qt422016.Writer, csrfToken, flash string, posts []types.Post) {
//line templates/index.qtpl:3
	qw422016.N().S(`
<div class="isu-submit">
  <form method="post" action="/" enctype="multipart/form-data">
    <div class="isu-form">
      <input type="file" name="file" value="file">
    </div>
    <div class="isu-form">
      <textarea name="body"></textarea>
    </div>
    <div class="form-submit">
      <input type="hidden" name="csrf_token" value="`)
//line templates/index.qtpl:13
	qw422016.E().S(csrfToken)
//line templates/index.qtpl:13
	qw422016.N().S(`">
      <input type="submit" name="submit" value="submit">
    </div>
    `)
//line templates/index.qtpl:16
	if flash != "" {
//line templates/index.qtpl:16
		qw422016.N().S(`
    <div id="notice-message" class="alert alert-danger">
      `)
//line templates/index.qtpl:18
		qw422016.E().S(flash)
//line templates/index.qtpl:18
		qw422016.N().S(`
    </div>
    `)
//line templates/index.qtpl:20
	}
//line templates/index.qtpl:20
	qw422016.N().S(`
  </form>
</div>

`)
//line templates/index.qtpl:24
	qw422016.E().S(PostsTemplate(posts))
//line templates/index.qtpl:24
	qw422016.N().S(`

<div id="isu-post-more">
  <button id="isu-post-more-btn">もっと見る</button>
  <img class="isu-loading-icon" src="/img/ajax-loader.gif">
</div>
`)
//line templates/index.qtpl:30
}

//line templates/index.qtpl:30
func WriteContentPage(qq422016 qtio422016.Writer, csrfToken, flash string, posts []types.Post) {
//line templates/index.qtpl:30
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/index.qtpl:30
	StreamContentPage(qw422016, csrfToken, flash, posts)
//line templates/index.qtpl:30
	qt422016.ReleaseWriter(qw422016)
//line templates/index.qtpl:30
}

//line templates/index.qtpl:30
func ContentPage(csrfToken, flash string, posts []types.Post) string {
//line templates/index.qtpl:30
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/index.qtpl:30
	WriteContentPage(qb422016, csrfToken, flash, posts)
//line templates/index.qtpl:30
	qs422016 := string(qb422016.B)
//line templates/index.qtpl:30
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/index.qtpl:30
	return qs422016
//line templates/index.qtpl:30
}
