// Code generated by qtc from "login.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line templates/login.qtpl:1
package templates

//line templates/login.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line templates/login.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line templates/login.qtpl:1
func StreamLoginPage(qw422016 *qt422016.Writer, flash string) {
//line templates/login.qtpl:1
	qw422016.N().S(`
<div class="header">
  <h1>ログイン</h1>
</div>

`)
//line templates/login.qtpl:6
	if flash != "" {
//line templates/login.qtpl:6
		qw422016.N().S(`
<div id="notice-message" class="alert alert-danger">
  `)
//line templates/login.qtpl:8
		qw422016.E().S(flash)
//line templates/login.qtpl:8
		qw422016.N().S(`
</div>
`)
//line templates/login.qtpl:10
	}
//line templates/login.qtpl:10
	qw422016.N().S(`

<div class="submit">
  <form method="post" action="/login">
    <div class="form-account-name">
      <span>アカウント名</span>
      <input type="text" name="account_name">
    </div>
    <div class="form-password">
      <span>パスワード</span>
      <input type="password" name="password">
    </div>
    <div class="form-submit">
      <input type="submit" name="submit" value="submit">
    </div>
  </form>
</div>

<div class="isu-register">
  <a href="/register">ユーザー登録</a>
</div>
`)
//line templates/login.qtpl:31
}

//line templates/login.qtpl:31
func WriteLoginPage(qq422016 qtio422016.Writer, flash string) {
//line templates/login.qtpl:31
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/login.qtpl:31
	StreamLoginPage(qw422016, flash)
//line templates/login.qtpl:31
	qt422016.ReleaseWriter(qw422016)
//line templates/login.qtpl:31
}

//line templates/login.qtpl:31
func LoginPage(flash string) string {
//line templates/login.qtpl:31
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/login.qtpl:31
	WriteLoginPage(qb422016, flash)
//line templates/login.qtpl:31
	qs422016 := string(qb422016.B)
//line templates/login.qtpl:31
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/login.qtpl:31
	return qs422016
//line templates/login.qtpl:31
}
