// Code generated by qtc from "post_id.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line templates/post_id.qtpl:1
package templates

//line templates/post_id.qtpl:1
import "github.com/catatsuy/private-isu/webapp/golang/types"

//line templates/post_id.qtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line templates/post_id.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line templates/post_id.qtpl:3
func StreamPostPage(qw422016 *qt422016.Writer, post types.Post) {
//line templates/post_id.qtpl:3
	qw422016.N().S(`
`)
//line templates/post_id.qtpl:4
	qw422016.E().S(PostTemplate(post))
//line templates/post_id.qtpl:4
	qw422016.N().S(`
`)
//line templates/post_id.qtpl:5
}

//line templates/post_id.qtpl:5
func WritePostPage(qq422016 qtio422016.Writer, post types.Post) {
//line templates/post_id.qtpl:5
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/post_id.qtpl:5
	StreamPostPage(qw422016, post)
//line templates/post_id.qtpl:5
	qt422016.ReleaseWriter(qw422016)
//line templates/post_id.qtpl:5
}

//line templates/post_id.qtpl:5
func PostPage(post types.Post) string {
//line templates/post_id.qtpl:5
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/post_id.qtpl:5
	WritePostPage(qb422016, post)
//line templates/post_id.qtpl:5
	qs422016 := string(qb422016.B)
//line templates/post_id.qtpl:5
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/post_id.qtpl:5
	return qs422016
//line templates/post_id.qtpl:5
}
