// Code generated by qtc from "post.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line templates/post.qtpl:1
package templates

//line templates/post.qtpl:1
import "github.com/catatsuy/private-isu/webapp/golang/types"

//line templates/post.qtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line templates/post.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line templates/post.qtpl:3
func StreamPostTemplate(qw422016 *qt422016.Writer, post types.Post) {
//line templates/post.qtpl:3
	qw422016.N().S(`
<div class="isu-post" id="pid_`)
//line templates/post.qtpl:4
	qw422016.N().D(post.ID)
//line templates/post.qtpl:4
	qw422016.N().S(`" data-created-at="`)
//line templates/post.qtpl:4
	qw422016.E().S(post.CreatedAt.Format("2006-01-02T15:04:05-07:00"))
//line templates/post.qtpl:4
	qw422016.N().S(`">
  <div class="isu-post-header">
    <a href="/@`)
//line templates/post.qtpl:6
	qw422016.E().S(post.User.AccountName)
//line templates/post.qtpl:6
	qw422016.N().S(`" class="isu-post-account-name">`)
//line templates/post.qtpl:6
	qw422016.E().S(post.User.AccountName)
//line templates/post.qtpl:6
	qw422016.N().S(`</a>
    <a href="/posts/`)
//line templates/post.qtpl:7
	qw422016.N().D(post.ID)
//line templates/post.qtpl:7
	qw422016.N().S(`" class="isu-post-permalink">
      <time class="timeago" datetime="`)
//line templates/post.qtpl:8
	qw422016.E().S(post.CreatedAt.Format("2006-01-02T15:04:05-07:00"))
//line templates/post.qtpl:8
	qw422016.N().S(`"></time>
    </a>
  </div>
  <div class="isu-post-image">
    <img src="`)
//line templates/post.qtpl:12
	qw422016.E().S(post.ImageURL)
//line templates/post.qtpl:12
	qw422016.N().S(`" class="isu-image">
  </div>
  <div class="isu-post-text">
    <a href="/@`)
//line templates/post.qtpl:15
	qw422016.E().S(post.User.AccountName)
//line templates/post.qtpl:15
	qw422016.N().S(`" class="isu-post-account-name">`)
//line templates/post.qtpl:15
	qw422016.E().S(post.User.AccountName)
//line templates/post.qtpl:15
	qw422016.N().S(`</a>
    `)
//line templates/post.qtpl:16
	qw422016.E().S(post.Body)
//line templates/post.qtpl:16
	qw422016.N().S(`
  </div>
  <div class="isu-post-comment">
    <div class="isu-post-comment-count">
      comments: <b>`)
//line templates/post.qtpl:20
	qw422016.N().D(post.CommentCount)
//line templates/post.qtpl:20
	qw422016.N().S(`</b>
    </div>

    `)
//line templates/post.qtpl:23
	for _, comment := range post.Comments {
//line templates/post.qtpl:23
		qw422016.N().S(`
    <div class="isu-comment">
      <a href="/@`)
//line templates/post.qtpl:25
		qw422016.E().S(comment.User.AccountName)
//line templates/post.qtpl:25
		qw422016.N().S(`" class="isu-comment-account-name">`)
//line templates/post.qtpl:25
		qw422016.E().S(comment.User.AccountName)
//line templates/post.qtpl:25
		qw422016.N().S(`</a>
      <span class="isu-comment-text">`)
//line templates/post.qtpl:26
		qw422016.E().S(comment.Comment)
//line templates/post.qtpl:26
		qw422016.N().S(`</span>
    </div>
    `)
//line templates/post.qtpl:28
	}
//line templates/post.qtpl:28
	qw422016.N().S(`
    <div class="isu-comment-form">
      <form method="post" action="/comment">
        <input type="text" name="comment">
        <input type="hidden" name="post_id" value="`)
//line templates/post.qtpl:32
	qw422016.N().D(post.ID)
//line templates/post.qtpl:32
	qw422016.N().S(`">
        <input type="hidden" name="csrf_token" value="`)
//line templates/post.qtpl:33
	qw422016.E().S(post.CSRFToken)
//line templates/post.qtpl:33
	qw422016.N().S(`">
        <input type="submit" name="submit" value="submit">
      </form>
    </div>
  </div>
</div>
`)
//line templates/post.qtpl:39
}

//line templates/post.qtpl:39
func WritePostTemplate(qq422016 qtio422016.Writer, post types.Post) {
//line templates/post.qtpl:39
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/post.qtpl:39
	StreamPostTemplate(qw422016, post)
//line templates/post.qtpl:39
	qt422016.ReleaseWriter(qw422016)
//line templates/post.qtpl:39
}

//line templates/post.qtpl:39
func PostTemplate(post types.Post) string {
//line templates/post.qtpl:39
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/post.qtpl:39
	WritePostTemplate(qb422016, post)
//line templates/post.qtpl:39
	qs422016 := string(qb422016.B)
//line templates/post.qtpl:39
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/post.qtpl:39
	return qs422016
//line templates/post.qtpl:39
}
