// Code generated by qtc from "posts.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line templates/posts.qtpl:1
package templates

//line templates/posts.qtpl:1
import "github.com/catatsuy/private-isu/webapp/golang/types"

//line templates/posts.qtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line templates/posts.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line templates/posts.qtpl:3
func StreamPostsTemplate(qw422016 *qt422016.Writer, posts []types.Post) {
//line templates/posts.qtpl:3
	qw422016.N().S(`
<div class="isu-posts">
  `)
//line templates/posts.qtpl:5
	for _, post := range posts {
//line templates/posts.qtpl:5
		qw422016.N().S(`
  `)
//line templates/posts.qtpl:6
		qw422016.N().S(PostTemplate(post))
//line templates/posts.qtpl:6
		qw422016.N().S(`
  `)
//line templates/posts.qtpl:7
	}
//line templates/posts.qtpl:7
	qw422016.N().S(`
</div>
`)
//line templates/posts.qtpl:9
}

//line templates/posts.qtpl:9
func WritePostsTemplate(qq422016 qtio422016.Writer, posts []types.Post) {
//line templates/posts.qtpl:9
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/posts.qtpl:9
	StreamPostsTemplate(qw422016, posts)
//line templates/posts.qtpl:9
	qt422016.ReleaseWriter(qw422016)
//line templates/posts.qtpl:9
}

//line templates/posts.qtpl:9
func PostsTemplate(posts []types.Post) string {
//line templates/posts.qtpl:9
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/posts.qtpl:9
	WritePostsTemplate(qb422016, posts)
//line templates/posts.qtpl:9
	qs422016 := string(qb422016.B)
//line templates/posts.qtpl:9
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/posts.qtpl:9
	return qs422016
//line templates/posts.qtpl:9
}
