// Code generated by qtc from "user.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line templates/user.qtpl:1
package templates

//line templates/user.qtpl:1
import "github.com/catatsuy/private-isu/webapp/golang/types"

//line templates/user.qtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line templates/user.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line templates/user.qtpl:3
func StreamUserPage(qw422016 *qt422016.Writer, user types.User, postCount, commentCount, commentedCount int, posts []types.Post) {
//line templates/user.qtpl:3
	qw422016.N().S(`
<div class="isu-user">
  <div><span class="isu-user-account-name">`)
//line templates/user.qtpl:5
	qw422016.E().S(user.AccountName)
//line templates/user.qtpl:5
	qw422016.N().S(`さん</span>のページ</div>
  <div>投稿数 <span class="isu-post-count">`)
//line templates/user.qtpl:6
	qw422016.N().D(postCount)
//line templates/user.qtpl:6
	qw422016.N().S(`</span></div>
  <div>コメント数 <span class="isu-comment-count">`)
//line templates/user.qtpl:7
	qw422016.N().D(commentCount)
//line templates/user.qtpl:7
	qw422016.N().S(`</span></div>
  <div>被コメント数 <span class="isu-commented-count">`)
//line templates/user.qtpl:8
	qw422016.N().D(commentedCount)
//line templates/user.qtpl:8
	qw422016.N().S(`</span></div>
</div>

`)
//line templates/user.qtpl:11
	StreamPostsTemplate(qw422016, posts)
//line templates/user.qtpl:11
	qw422016.N().S(`
`)
//line templates/user.qtpl:12
}

//line templates/user.qtpl:12
func WriteUserPage(qq422016 qtio422016.Writer, user types.User, postCount, commentCount, commentedCount int, posts []types.Post) {
//line templates/user.qtpl:12
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/user.qtpl:12
	StreamUserPage(qw422016, user, postCount, commentCount, commentedCount, posts)
//line templates/user.qtpl:12
	qt422016.ReleaseWriter(qw422016)
//line templates/user.qtpl:12
}

//line templates/user.qtpl:12
func UserPage(user types.User, postCount, commentCount, commentedCount int, posts []types.Post) string {
//line templates/user.qtpl:12
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/user.qtpl:12
	WriteUserPage(qb422016, user, postCount, commentCount, commentedCount, posts)
//line templates/user.qtpl:12
	qs422016 := string(qb422016.B)
//line templates/user.qtpl:12
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/user.qtpl:12
	return qs422016
//line templates/user.qtpl:12
}
