name: CD to AWS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v5
        with:
          go-version: "1.23"

      - name: build
        run: |-
          cd webapp/golang
          go build -o app .
      - name: deploy
        run: |-
          mkdir -m 700 -p ~/.ssh 
          echo "${{ secrets.PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh -o "StrictHostKeyChecking no" isucon@isu-worker.grainrigi.net rm -rf "~/private_isu/webapp/golang"
          scp -r webapp/golang isucon@isu-worker.grainrigi.net:~/private_isu/webapp/golang
          ssh ubuntu@isu-worker.grainrigi.net sudo systemctl restart isu-go
